const testTypes = {
    REQUEST_EASY_TEST: "REQUEST_EASY_TEST",
    EASY_TEST_SUCCESS: "EASY_TEST_SUCCESS",
    EASY_TEST_FAILURE: "EASY_TEST_FAILURE",
    REQUEST_API_TEST: "REQUEST_API_TEST",
    API_TEST_SUCCESS: "API_TEST_SUCCESS",
    API_TEST_FAILURE: "API_TEST_FAILURE"
}

export default testTypes
